### ISSUE TITLE
Enthalpy of vaporization

### ISSUE THREAD

**Issue by ramess101** [ramess101/MBAR_GCMC#10]
@msoroush @jpotoff

I am computing the heat of vaporization using the following equation (from Mick et al.):

![image](https://user-images.githubusercontent.com/23408516/47114488-30d3c380-d219-11e8-99b2-072de78abb62.png)

However, there is a clear bias between the MBAR DeltaHv values and those reported by Mick et al. with histogram reweighting (HR):

![image](https://user-images.githubusercontent.com/23408516/47114577-72fd0500-d219-11e8-9aee-32938a85cd92.png)

I was hoping you could help me elucidate the cause for this deviation. Recall that the rholiq, rhovap, and Psat values do not demonstrate any bias:

![image](https://user-images.githubusercontent.com/23408516/47114676-c0797200-d219-11e8-95b1-7100b07bb97f.png)

So it appears the bias has to be coming from the Uv-Ul term. Just to verify, do these U values include the intramolecular difference (which can be non-negligible for a high density liquid and a low density vapor)? If so, I think the histogram values that Mohammad provided me with only have U for the non-bonded contribution, correct?

If not, is it possible that the small biases in rhov and/or Psat are magnified when computing DeltaHv? In other words, do you think this could just be a propagation of errors scenario?

**Comment by mrshirts** [comment]
Well, it's possible the histogram values are the ones that are wrong . . . : )

But yes, one would have to look at intramolecular energy differences if there are any as well.

**Comment by jpotoff** [comment]
@ramess101 that is weird.  The histogram data we sent you has just the intermolecular energies.  As far as the effect of combining small errors = a bigger error, I don't think you should see that here.  We do see small errors combining into large errors in the calculation of the compressibility factor, though.  It would be worth calculating Z and seeing what you get.

**Comment by ramess101** [comment]
@mrshirts 

> But yes, one would have to look at intramolecular energy differences if there are any as well.

I agree that the intramolecular differences SHOULD be included, but they are often neglected. The real purpose of this exercise is to compare MBAR and HR, so what we really need to know is whether they WERE included by Mick et al. @msoroush @jpotoff  you mentioned that the histogram data only had intermolecular energies, but do you know if the intramolecular energies were also included for computing DeltaHv? If so, are the files with the intramolecular snapshots easily accessible?

> It would be worth calculating Z and seeing what you get.

I will look into this.

**Comment by jpotoff** [comment]
@ramess101 @msoroush @mrshirts 
In this case, the change in the intramolecular energies between phases was small (< 1%) and they were neglected in the dHv calculation.  We know that for larger, more flexible molecules, that approximation isn't going to work, and one must include the intramolecular contributions to get dHv right.  Unfortunately, we did not histogram the intramolecular energies, and getting them would require running new simulations.

**Comment by ramess101** [comment]
@jpotoff 

OK, well I really am just trying to replicate your values. So if you did not include the intramolecular energies, then that is what I will do. No need to run new simulations. But I will need to elucidate what the cause is for this discrepancy. 

As for Z, the uncertainties are large but there is no bias, i.e. our results are consistent:

![image](https://user-images.githubusercontent.com/23408516/47127207-6abcbe00-d249-11e8-8493-d927ee3d51de.png)

**Comment by jpotoff** [comment]
@ramess101 Just throwing an idea out there, and maybe this is the issue because our equation isn't written exactly right.  In our calculation we are taking the difference of the average energy (and molar volumes) in each phase.  <U_V>-<U_L>+P(<V_G>-<V_L>)

**Comment by ramess101** [comment]
@jpotoff 

That is almost how I am computing it as well. I am using <U> but I am
actually computing the volumes as 1/<rho>, maybe that is a problem? I kind
of doubt it, but I will try it out tomorrow.

Another idea that might impact low density vapor energies, do you include
snapshots in the averaging where the number of molecules is 0? I think
there are quite a few and this could impact Uvap and/or Vvap. But this
wouldnt explain the divergence at high temperatures.

**Comment by ramess101** [comment]
@jpotoff 

I have confirmed that the P DeltaV contribution is not the problem:

![image](https://user-images.githubusercontent.com/23408516/47164493-60d0a480-d2b5-11e8-821c-4a259e9275cd.png)

The DeltaUv term is clearly where the bias in DeltaHv is coming from:

![image](https://user-images.githubusercontent.com/23408516/47164581-88c00800-d2b5-11e8-8e12-881d038ea65c.png)

**Comment by ramess101** [comment]
@mrshirts @jpotoff 

OK, I think I found the problem. < Uv > and < Ul > are the ensemble average internal energies per mol. U in the simulation output is internal energy per N molecules (U_perN). Previously, I was dividing U_perN by N to get internal energy per molecule (and then multiple by Avogadro's number) when determining the ensemble average of U. In other words, I had been using < Uv > = < Uv_perN / Nv >. But if I instead take the ensemble average of U_perN and divide that by the ensemble average of N, i.e., < Uv > = < Uv_perN > / < Nv > I get much better agreement:

![image](https://user-images.githubusercontent.com/23408516/47166544-a8592f80-d2b9-11e8-94c1-7b32929933ee.png)

@jpotoff Do you know if Mick et al. used < U_perN / N > or < UperN > / < N >?

**Comment by mrshirts** [comment]
Thanks for catching that.  Still a good question what the right equation is.  One quick question though - if you calculate <Uv_per N> for different numbers of N, is it constant, or does it vary?  If it varies, that's a bit of information to use . . .

**Comment by ramess101** [comment]
@mrshirts 

> Still a good question what the right equation is.

True. I don't know which is more correct.

> <Uv_per N> for different numbers of N, is it constant, or does it vary?

I will look into this

**Comment by ramess101** [comment]
Yes <Uv_per N> does vary with respect to N (recall the curvature in the U vs N histogram plots)
