### ISSUE TITLE
Argon

### ISSUE THREAD

**Issue by ramess101** [ramess101/MBAR_GCMC#6]
Because I am having problems with the absolute pressures for hexane, I am now going to try with argon since this compound is used in the workshop: https://github.com/GOMC-WSU/Workshop/blob/master/GCMC/argon. This should facilitate debugging as I can compare my intercept value with the value they reported.

Here are the histogram plots from the seven state points that I simulated with GOMC:

![image](https://user-images.githubusercontent.com/23408516/41042346-a8b1ee64-695e-11e8-862c-a5b21da30e4c.png)

![image](https://user-images.githubusercontent.com/23408516/41042351-abea5c7e-695e-11e8-9dfb-d412c821b4cc.png)

**Comment by ramess101** [comment]
First, I verify that I get the same rhov and rhol points as reported by Mick et al.:

![image](https://user-images.githubusercontent.com/23408516/41043934-41cfaae8-6962-11e8-9c81-e04e64ce7788.png)

**Comment by ramess101** [comment]
Here are the results from my analysis compared with the reported intercept value from the workshop file 

https://github.com/GOMC-WSU/Workshop/blob/master/GCMC/argon/patch/phinput.idat

![image](https://user-images.githubusercontent.com/23408516/41045370-87d1468e-6965-11e8-9a45-f7ba03e1148e.png)

Slope for ideal gas is 1, actual slope is: 0.999996090033
Intercept for absolute pressure is:-2.43235462657

@msoroush Can you verify for me that the value of -2.4061 in the workshop argon phinput.idat is the correct intercept? If it is, I need to figure out why my intercept is so different.

**Comment by msoroush** [comment]
@ramess101, Here is my results. You can try the hist file that I attached and use the chemical potential listed in pvt.idat to calculate the molecule number and ln of partition function.
![intercep](https://user-images.githubusercontent.com/13317444/41047042-a7e7e8b0-6979-11e8-86c0-ee7587944824.png)



[argon.tar.gz](https://github.com/ramess101/MBAR_GCMC/files/2076856/argon.tar.gz)

**Comment by ramess101** [comment]
@msoroush 

Thank you for getting back to me. My intercept actually only differs from yours by about 0.02. This would not lead the large deviations in absolute pressure that I am observing. Furthermore, if I use the histogram that you provided, I get the exact same intercept: 

![image](https://user-images.githubusercontent.com/23408516/41051335-0bfe2532-6973-11e8-820e-99a4c5d2e98e.png)

Slope for ideal gas is 1, actual slope is: 0.999997682922
Intercept for absolute pressure is:-2.45489349921

So this demonstrates that the lnZ0 term is not the reason my pressures are so off. This was very helpful, as I can now look somewhere else for the bug in my code.

**Comment by ramess101** [comment]
@msoroush 

I continue to have an error in my pressures. To figure out what the problem is, it would be very helpful if I had your Zliq values that are used to compute the pressures. 

I tried to compute Zliq myself using your code. Specifically, I followed the README instructions in the workshop (https://github.com/GOMC-WSU/Workshop/tree/master/GCMC/argon) to run the patch/program files on my own histograms, but I kept getting this error when I tried to run ./pvt.out:

PHASE VERSION 8.0
 PVT MODE
At line 178 of file pvt.f90 (unit = 2, file = 'input_fsp2.dat')
Fortran runtime error: Bad real number in item 5 of list input

We could try to figure out why I am getting this error, but it would probably be easier and faster if you just ran your code on my histograms (see attachement). Could you analyze these histograms and provide me with the Zliq and pressure values? 

Thanks

[ram9his.zip](https://github.com/ramess101/MBAR_GCMC/files/2080763/ram9his.zip)

**Comment by msoroush** [comment]
@ramess101 try to delete weights.dat and input_fsp2.dat files. Then try again following [README](https://github.com/GOMC-WSU/Workshop/tree/master/GCMC/argon/patch) file. I had the same issue, this would solve your problem.

**Comment by msoroush** [comment]
@ramess101  here are the results for pressure, liquid and vapor densities and Z. pcov generate the pressure in tp.dat and trho.dat for densities, but it does not calculate the Z. You can double check my calculation for Z.
[argon.dat.zip](https://github.com/ramess101/MBAR_GCMC/files/2080918/argon.dat.zip)

**Comment by ramess101** [comment]
@msoroush 

Thanks. Your code seems to be working for me now. I verified that our weights are the same for each of the 7 simulation points, i.e. my code gives the same values as the weights.dat file. But for some reason there is a nearly constant deviation of -0.69 in our lnZliq values.

**Comment by ramess101** [comment]
@msoroush 

I was able to find the lnZliq values in phase.dat

**Comment by ramess101** [comment]
@msoroush 

Sorry, I think I confused you when I kept saying Z. I was referring to the partition function (specifically, lnZliq), not the compressibility factor.

**Comment by msoroush** [comment]
:D

**Comment by mrshirts** [comment]
-0.69 = -ln 1.9937 . . .   ? Loose factor of 2 anywhere?

**Comment by ramess101** [comment]
Hmmm... so maybe somewhere I am missing a -ln(2)

**Comment by ramess101** [comment]
@mrshirts 

OK, all I can think of is that I need to divide by 2 somewhere to account for the liquid and vapor phases.  Currently this is how I get the lnZliq:

Deltaf_ij = mbar.getFreeEnergyDifferences[0]
lnZliq = Deltaf_ij[nTsim:,0] #nTsim is the number of simulated temperatures. nTsim: yields the Deltaf_ij values for only the VLE (non-simulated) mu,T points

press = kT/V*(lnZliq - lnZ0)

But we get the correct pressure if we use:

press = kT/V*(lnZliq - ln(2) - lnZ0)

Since @msoroush and I got the same lnZ0 values for the ideal gas intercept, this suggests that:

lnZliq_correct = ln(Zliq/2)

Since Zliq = exp(Deltaf_ij), this would mean that the exp(Deltaf_ij[nTsim:]) needs to be divided by 2. @mrshirts can you think of why this would be true? Again, my only guess is that somehow this needs to account for the two phases.

These equations from Issue #1 might help

![image](https://user-images.githubusercontent.com/23408516/41113356-a23f6b98-6a3e-11e8-8110-92c664b3799b.png)

Note that Ci is Deltaf_ij, so exp(Ci) is exp(Deltaf_ij), which is equal to the sum over all E and N of p.

**Comment by ramess101** [comment]
@msoroush @mrshirts 

Also, note that the -ln(2) term not only fixed my argon pressures but also my hexane pressures. So I think this really was the problem.

Thanks again for helping me resolve this issue! Now we just need to be able to explain it.

**Comment by mrshirts** [comment]
It's not entirely clear to me where this difference is occuring from.  If @msoroush ISN'T seeing this, and is using the same histograms, can you compare their code? Is it possible the error is in that code?

**Comment by ramess101** [comment]
This snippet from https://github.com/GOMC-WSU/Workshop/blob/master/GCMC/argon/patch/program/phase.f90

		`if(n(1,ifile)%flength(i).lt.nmid(tnum)+split)` then
  			Zgas = Zgas + exp(-ylog)

                       nbelow = nbelow + exp(-ylog)
                        do icomp = 1,ncomp
                           ngas(icomp) = ngas(icomp) + &
			   n(icomp,ifile)%flength(i)*exp(-ylog)
                        enddo
                        energy_gas = energy_gas + &
                             e(ifile)%flength2(i)*exp(-ylog)
		else 
  			Zliq = Zliq + exp(-ylog)

                        do icomp = 1,ncomp
                           nliq(icomp) = nliq(icomp) +&
			   n(icomp,ifile)%flength(i)*exp(-ylog)
                        enddo
                        energy_liq = energy_liq + &
                             e(ifile)%flength2(i)*exp(-ylog)
                end if`

clearly shows that Zliq and Zgas are only added to when N is greater and less than Nmid, respectively.

**Comment by ramess101** [comment]
> If @msoroush ISN'T seeing this, and is using the same histograms, can you compare their code? Is it possible the error is in that code?

@mrshirts 

I am very confident in their code. My original pressures had some serious issues that were clear red flags that my code had the problem. For example, my logP vs 1/T trend was very strange. Also, at low Tsat where the vapor is nearly ideal (because vapor pressure is very low) my pressures were not converging to the ideal gas value. 

Note that these results were using my MBAR-GCMC code. I have not tried to fix my histogram reweighting code because it had some other issues that were not worth debugging.

**Comment by mrshirts** [comment]
Are there the same number of molecules in the liquid and vapor phase?  Do you get a different correction factor if the number is uneven?

**Comment by ramess101** [comment]
@mrshirts 

The number of molecules in each phase is quite different because the volumes are equal.

**Comment by mrshirts** [comment]
I can't think of a physical justification for "there are two phases, so divide by 2".  What is the ratio of the volumes that are used?

**Comment by ramess101** [comment]
@mrshirts 

The volumes are the same. 

My explanation is the following:

For traditional histogram reweighting, in Equation 15 we compute exp(Ci), which is the same as exp(Deltaf_ij) in MBAR lingo, by summing the probabilities of all the bins. 

![image](https://user-images.githubusercontent.com/23408516/41116109-9e211068-6a46-11e8-93d2-6b6e9d656d40.png)

As shown in @msoroush code above, this summation is broken into two terms, Zliq and Zgas, based on the Nmid (i.e., low N adds to Zgas and high N adds to Zliq). So I think essentially what I have been using is Zliq+Zgas, which at VLE equilibrium these are the same, and thus we have exp(Deltaf_ij) = 2*Zliq.

**Comment by mrshirts** [comment]
Ah, OK. If the simulation uses the total energy and total N over all boxes (i.e. semigrand), then yes, it's the total partition function.  The partition functions of the phases aren't equal at equilibrium, but pressures should be, so for NmuT, then P V = /propto Z, so for equal volumes, then you would have the total Z = 2*liquid Z.  You could check this by running a simulation with a different (fixed) volume for the gas, and reconstructing what the correction term is in that case.

**Comment by ramess101** [comment]
@mrshirts 

> If the simulation uses the total energy and total N over all boxes (i.e. semigrand), then yes, it's the total partition function. The partition functions of the phases aren't equal at equilibrium, but pressures should be, so for NmuT, then P V = /propto Z, so for equal volumes, then you would have the total Z = 2*liquid Z. 

OK, that makes more sense.

> You could check this by running a simulation with a different (fixed) volume for the gas, and reconstructing what the correction term is in that case.

That would be interesting. I think we can revisit this idea later, once we have everything else working well.
